name: CI

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: true
      matrix:
        elixir: [1.9.x, 1.8.x, 1.7.x]
        otp: [22.3, 21.2, 20.2]

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: CI - Elixir ${{ matrix.elixir }} - OTP ${{ matrix.otp }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Install Mix dependencies
      run: mix deps.get

    - name: Upload coverage to Coveralls
      run: mix coveralls.github

    - name: Install Mix dependencies
      run: MIX_ENV=docs mix deps.get

    - name: Upload report to Inch
      run: MIX_ENV=docs mix inch.report
